export const work = [
  {
    id: 0,
    title: '콘텐츠 웨이브',
    date: '2022.03.06 - 현재',
    md: require('../markdown/project/wavve.md'),
    tag: [
      'Vue',
      'Typescript',
      'Pinia',
      'TDD',
      'Vue Query',
      'UnoCSS',
      'Storybook',
      'SSR',
    ],
    img: require('../assets/wavve.png'),
  },
  {
    id: 1,
    title: '더풀네트워크',
    date: '2022.06.15 - 2022.09.13',
    md: require('../markdown/project/pool.md'),
    tag: [
      'Typescript',
      'React Native',
      'React Query',
      'Redux',
      'Webpack',
      'Firebase',
    ],
    img: require('../assets/pool_logo.png'),
  },
];
export const personal = [
  {
    id: 0,
    title: 'TEOConf 2023',
    date: '2023.05.20',
    md: require('../markdown/project/teoconf.md'),
    tag: ['Conference', 'Speaker'],
    img: require('../assets/teoconf.webp'),
  },
  {
    id: 1,
    title: 'Simple Thumbnail',
    date: '2023.02.22 - 2023.02.27',
    md: require('../markdown/project/simpleThumbnail.md'),
    tag: ['React', 'Typescript', 'Tailwind CSS', 'BDD'],
  },
  {
    id: 2,
    title: '흑끼의 마법떡집',
    date: '2022.12.18 - 2022.12.25',
    md: require('../markdown/project/blackrabbit.md'),
    tag: ['Typescript', 'React', 'Github Pages', 'Workflows'],
  },
  {
    id: 3,
    title: '초성편지',
    date: '2022.09.28 - 2022.10.05',
    md: require('../markdown/project/csletter.md'),
    tag: ['Typescript', 'React', 'AWS S3', 'AWS Cloud Front'],
  },
  {
    id: 4,
    title: 'Likelion Apply Crawler',
    date: '2021.04',
    md: require('../markdown/project/likelionCrawler.md'),
    tag: ['Python', 'Selenium'],
  },
  {
    id: 5,
    title: '멋쟁이사자처럼',
    date: '2020.10 - 2022.12',
    md: require('../markdown/project/likelion.md'),
    tag: ['React ', 'Javascript', 'Python', 'Adobe XD', 'Zeplin'],
    img: require('../assets/likelion.png'),
  },
  {
    id: 6,
    title: '광주인공지능사관학교',
    date: '2020.05 - 2020.12',
    md: require('../markdown/project/aischool.md'),
    tag: ['Python', 'Web', 'Django', 'ML', 'DL'],
    img: require('../assets/aischool.png'),
  },
  {
    id: 7,
    title: '코띵한 와사비',
    date: '2020.12 - 2022',
    md: require('../markdown/project/wasabi.md'),
    tag: ['React', 'Adobe XD'],
    img: require('../assets/wasabi.png'),
  },
];
